import turtle
def t1():
    wn = turtle.Screen()     # creates a graphics window
    wn.setup(500,440)      # set window dimension

    t = turtle.Turtle()
    t.color('red')
    t.forward(100)
    t.left(90)
    t.forward(80)
    t.right(90)
    t.circle(36)
    t.write("DELI",move=False,align="center",font=('calibri',18,'bold'))
    b = turtle.Turtle()
    b.color('blue')
    b.left(90)
    b.forward(100)
    b.left(90)
    b.forward(50)
    b.circle(36)
    b.write("HEALTH",move=False,align="center",font=('calibri',18,'bold'))
    g = turtle.Turtle()
    g.color('green')
    g.right(90)
    g.forward(130)
    g.left(90)
    g.forward(50)
    g.circle(36)
    g.write("HOME",move=False,align="center",font=('calibri',18,'bold'))
    g1 = turtle.Turtle()
    g1.color('orange')
    g1.backward(110)
    g1.left(90)
    g1.forward(50)
    g1.circle(36)
    g1.write("DRIED",move=False,align="center",font=('calibri',18,'bold'))
    g2 = turtle.Turtle()
    g2.color('brown')
    g2.right(90)
    g2.forward(10)
    g2.right(90)
    g2.forward(110)
    g2.left(90)
    g2.forward(50)
    g2.circle(36)
    g2.write("PACKED",move=False,align="center",font=('calibri',18,'bold'))

t1()
